stateDiagram-v2
    [*] --> coalesce_single
    coalesce_single --> cll.initialize_ids_members
    coalesce_single --> cache_collection

    state if_state<<choice>>
    cache_collection --> if_state
    if_state --> coalesce_torrents_per_hour : hour
    coalesce_torrents_per_hour --> coalesce_each_hour
    if_state --> persistent_collection_per : hour, persistp

    if_state --> coalesce_torrents_per_day : day
    if_state --> persistent_collection_per : day, persistp

    if_state --> coalesce_torrents_per_week : week
    if_state --> persistent_collection_per : week, persistp

    if_state --> coalesce_torrents_cumulative : cumulative