stateDiagram-v2
    [*] --> coalesce_single
    coalesce_single --> cll.initialize_ids_members
    coalesce_single --> cache_collection

    state if_state<<choice>>
    cache_collection --> if_state

    if_state --> coalesce_torrents_per_hour : hour
    coalesce_torrents_per_hour --> coalesce_each_hour
    coalesce_each_hour --> persistent_collection_per : persistp

    if_state --> coalesce_torrents_per_day : day
    coalesce_torrents_per_day --> persistent_collection_per : persistp

    if_state --> coalesce_torrents_per_week : week
    coalesce_torrents_per_week --> persistent_collection_per : persistp

    if_state --> coalesce_torrents_cumulative : cumulative